[Feat] ExploreShortcutView 관련 UI 구현
Team-ShortcutsZip/MacC-Team-HappyAnding pull request #519
Opened 2024-04-02 15:31 UTC by JMM00

## 📌 해결하려는 이슈

- closes #518 

## ✨핵심적인 변경사항

- ExploreShortcutView
    - PromotionSection / PromotionCard 
        - 기존 AdminCurationCell에서 PromotionCard로 변경하여 새롭게 구현했습니다.
        - 기존 Curation 데이터를 기준으로 작업했으며, 현재 데이터 구조 상 shortDescription의 부재로 추후 적용이 필요합니다.
        - 추후 배경 이미지 적용이 별도로 필요합니다.
    - 단축어 셀
        - 셀 타입을 ordered/unordered 로 구분하여 구현했습니다.
    - 단축어 리스트
        - 기존에 SectionType이 존재하여 ExploreShortcutSectionType으로 명명하여 [.new, .mostDownloaded, .mostloved] 의 세가지 타입으로 나눠서 정의했습니다.
        - 추후 SectionType으로 이름 변경이 필요합니다. 
    - 검색바
        - section header로 적용되어있으며 현재 배경색에 opacity 적용으로 별도의 배경색 지정이 필요합니다.
        - 검색바 접근 시 화면 동작 방식에 대해서 논의가 필요합니다.

- ExpandedRankingView
    - 해당 화면에서 사용되는 셀을 구현했습니다.
    - 우측 상단 버튼의 기능과 아이콘 셀의 디자인 확인이 필요합니다.
    - 각 리스트 타입 별 나열되는 수는 추후 적용이 필요합니다.

## 🔖 그 외 변경사항 

- SCZ+Color 
    -  스타일 가이드와 피그마 변수들을 참고하여 색상을 적용하기 위해 임의로 추가했습니다. 
    - 추가된 색상은 모두 이 파일에서 코드 상으로 정의되었습니다.
    - 추후 구조 변경 또는 삭제 될 파일입니다.
- Promotion Card 배경이미지 추가
- OrderedCell 순서 배경 이미지 (Seal) 추가

## 📱 스크린샷

| 스크린샷1 | 스크린샷2 | 
|:---:|:---:|
|![Simulator Screenshot - iPhone 15 - 2024-04-02 at 23 57 54](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/2db0b7ea-d079-4089-b059-2d5448b672e8)|![Simulator Screenshot - iPhone 15 - 2024-04-02 at 23 58 02](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/2ae3eb7c-030e-4534-baf4-abdd6a4ffe1b)|

2024-04-03 08:01 UTC, HanGyeongjun requested changes
수고하셨습니다!
SCZColor가 생겨서 새로운 색상 사용하는 데 수월해지겠네요..! 다크모드 대응과 다양한 그라디언트도 다 적용되어 있어서 편하게 쓸 수 있을 것 같습니다.

## 수정 요청
- CardSection에서 카드 양쪽이 잘리는 현상이 발생합니다! padding 값 적용 위치 수정해서 왼쪽 오른쪽 스크롤 했을 때 개별 카드가 화면 끝까지 보여야 할 것 같습니다
<img width="381" alt="Screenshot 2024-04-03 at 16 16 54" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/8ff39214-6b4f-46df-9089-592548a1cd43">
- 색상 적용 중 SCZColor로 적용되지 않은 부분들 수정 부탁드림니당
- 텍스트 TextLiteral로 분리 부탁드립니다
- 

## 제안/질문
- PromotionSection의 가로 캐로셀의 동작이 일반적인 사용 패턴에서 불편하게 느껴질 수 있을 것 같습니다..! 지금 스크롤이 절반 이상 되었을 떄 다음 카드로 스냅되는 것으로 보이는데 생각보다 신경 써서 카드를 넘겨야 다음으로 넘어가네요😭 약간 빠르게 넘기다 보면 종종 원래 위치로 되돌아오는 현상이 생깁니다. 다른 분들 의견도 들어봐야 할 것 같아요.
- 공통적으로 디자인에 사용되는 요소들을 extension등으로 분리해 재사용성을 높이는 방향이 좋을 것 같습니다!
    - RoundedRectangle 및 윤곽선 : #516 에서 extension으로 구현해놨습니다
    - 숫자 seal?
    - 그라디언트 적용 : SCZColor서 이미 같은 기능을 하는 것으로 보이는데 맞나요?
- 화면의 Background 색상은 다음 태스크에서 적용 예정이신가요?

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Assets.xcassets/Seal.imageset/Seal.png
SF Symbol이 아닌 별도의 PNG 에셋으로 등록하신 이유가 있을까요??

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Model/ExploreShortcutSectionType.swift
> +                Text("새로 올라온")
TextLiteral로 분리 부탁드림니당

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Model/ExploreShortcutSectionType.swift
> +                        Color(hexString: "404040", opacity: 0.48)
등록해두신 SCZColor의 CharcoalGray.48 쓸 수 있을 것 같아요

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/Components/CardSection.swift
> +        }
다크모드일 때는 괜찮은데 라이트 모드일 때 대비가 너무 적어서 텍스트가 잘 안 보임니다 ㅜㅜ 디자인 변경이 필요해보여요! @teethemoji

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExpandedRankingView.swift
> +        }
blendMode도 다 달랐군요...👀

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/Components/ShortcutIcon.swift
> +    let sfsymbol: String
```suggestion
    let sfSymbol: String
```

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/Components/ShortcutIcon.swift
> +            Image(systemName: sfsymbol)
```suggestion
            Image(systemName: sfSymbol)
```

2024-04-03 08:09 UTC, HanGyeongjun commented on HappyAnding/HappyAnding/Views/Components/ShortcutIcon.swift
> +    ShortcutIcon(sfsymbol: "play.rectangle.fill", color: "Red", size: 56)
```suggestion
    ShortcutIcon(sfSymbol: "play.rectangle.fill", color: "Red", size: 56)
```

2024-04-03 08:14 UTC, JMM00 commented
@HanGyeongjun 
디자인 수정사항 말고 레이아웃만 봐주시겠어요? 아직 디자인 확정사항 아니고 색상 확정아니고, 익스텐션 제작된게 없어서 제가 작업하기 편하려고 임의로 작성해서 사용했다고 적어뒀습니다~
카드섹션은 어떤 상황에서 말하는건지 모르겠어요 다시 한번 설명 부탁드립니다

2024-04-03 08:17 UTC, JMM00 commented on HappyAnding/HappyAnding/Assets.xcassets/Seal.imageset/Seal.png
SF Symbol 인지 몰라서요^^

2024-04-03 08:18 UTC, JMM00 commented on HappyAnding/HappyAnding/Model/ExploreShortcutSectionType.swift
> +                        Color(hexString: "404040", opacity: 0.48)
어차피 임시로 사용한 파일이라 바뀔거 생각하고 이전 작업 사항에는 반영안해뒀습니다. 컬러 익스텐션 확정 된 후에 반영해도 충분할 것 같습니다.

2024-04-03 08:18 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/Components/CardSection.swift
> +        }
피그마 파일에서 코멘트 요청하는게 더 빠를 것 같아요

2024-04-03 08:18 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/Components/ShortcutIcon.swift
> +            Image(systemName: sfsymbol)
^^

2024-04-03 08:19 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/Components/ShortcutIcon.swift
> +    ShortcutIcon(sfsymbol: "play.rectangle.fill", color: "Red", size: 56)
^^

2024-04-03 08:23 UTC, HanGyeongjun commented
> @HanGyeongjun 디자인 수정사항 말고 레이아웃만 봐주시겠어요? 아직 디자인 확정사항 아니고 색상 확정아니고, 익스텐션 제작된게 없어서 제가 작업하기 편하려고 임의로 작성해서 사용했다고 적어뒀습니다~ 카드섹션은 어떤 상황에서 말하는건지 모르겠어요 다시 한번 설명 부탁드립니다
> 
> 확정된 익스텐션 존재한다면 먼저 pr올려주시면 더 좋을 것 같네요

SCZColor가 임의로 만드신거긴 한데 사용 방법도 편리하고 다양한 색상 사용에 대응이 가능할 것 같아서 저는 계속 유지해도 좋을 것 같다는 의견이었습니다! 사용 색상 확정되면 그 부분만 수정해서 그대로 쓰면 될 것 같아요.
지난번에 티모가 색상 hex값으로 사용하자고 하신 기억도 있어서 괜찮아 보임니당

<img width="1036" alt="Screenshot 2024-04-03 at 17 25 11" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/a290563c-10df-4366-a644-a9592ac97f55">

여기 양쪽 부분에서 카드가 끝까지 보여야 할 것 같습니다! 지금은 양쪽 padding 때문에 끝까지 나타나지 않네요

익스텐션은 지금 작업중인 브랜치라 오늘 밤 중에 pr 올릴 수 있을 것 같아요😭

2024-04-03 08:25 UTC, JMM00 commented
> > @HanGyeongjun 디자인 수정사항 말고 레이아웃만 봐주시겠어요? 아직 디자인 확정사항 아니고 색상 확정아니고, 익스텐션 제작된게 없어서 제가 작업하기 편하려고 임의로 작성해서 사용했다고 적어뒀습니다~ 카드섹션은 어떤 상황에서 말하는건지 모르겠어요 다시 한번 설명 부탁드립니다
> > 확정된 익스텐션 존재한다면 먼저 pr올려주시면 더 좋을 것 같네요
> 
> SCZColor가 임의로 만드신거긴 한데 사용 방법도 편리하고 다양한 색상 사용에 대응이 가능할 것 같아서 저는 계속 유지해도 좋을 것 같다는 의견이었습니다! 사용 색상 확정되면 그 부분만 수정해서 그대로 쓰면 될 것 같아요. 지난번에 티모가 색상 hex값으로 사용하자고 하신 기억도 있어서 괜찮아 보임니당
> 
> ![Image](https://private-user-images.githubusercontent.com/94854258/319101524-e6fa4c25-4989-4191-8fe3-96c66f74510d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzI5ODksIm5iZiI6MTcxMjEzMjY4OSwicGF0aCI6Ii85NDg1NDI1OC8zMTkxMDE1MjQtZTZmYTRjMjUtNDk4OS00MTkxLThmZTMtOTZjNjZmNzQ1MTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4MjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNTI2MDIyYTJjODY4NWQ2NzEwNGUxZTQ0OGVhZGQxNTA5YTI4YzgwNzBmMzIzMTUzZTVhMDZlNjNlZjA0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.221jAbhN5EXqb4ex6hDaqmFOu1z25DvKxvAWehsR86E) 여기 양쪽 부분에서 카드가 끝까지 보여야 할 것 같습니다! 지금은 양쪽 padding 때문에 끝까지 나타나지 않네요
> 
> 익스텐션은 지금 작업중인 브랜치라 오늘 밤 중에 pr 올릴 수 있을 것 같아요😭

공통으로 적용해야하는 익스텐션을 먼저 작업중이셨다면 브랜치를 분리해서 먼저 올려줬으면 더 좋았을 것 같네요
이미지 깨져서 안보여요

2024-04-03 08:33 UTC, teethemoji commented
> 수고하셨습니다! SCZColor가 생겨서 새로운 색상 사용하는 데 수월해지겠네요..! 다크모드 대응과 다양한 그라디언트도 다 적용되어 있어서 편하게 쓸 수 있을 것 같습니다.
> 
> ## 수정 요청
> * CardSection에서 카드 양쪽이 잘리는 현상이 발생합니다! padding 값 적용 위치 수정해서 왼쪽 오른쪽 스크롤 했을 때 개별 카드가 화면 끝까지 보여야 할 것 같습니다
> 
> <img alt="Screenshot 2024-04-03 at 16 16 54" width="381" src="https://private-user-images.githubusercontent.com/94854258/319080619-8ff39214-6b4f-46df-9089-592548a1cd43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzI2ODcsIm5iZiI6MTcxMjEzMjM4NywicGF0aCI6Ii85NDg1NDI1OC8zMTkwODA2MTktOGZmMzkyMTQtNmI0Zi00NmRmLTkwODktNTkyNTQ4YTFjZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OGRmMzY1NGNiZWMxNTMxZDU0NTAyMDI2YTc3MDlmYmRiZDc3YmNjNjQ2ZjE5ODYxMjhmZGY0MTQ0ZGRjMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L-TXfRwHftLAi-0M2pP_7gjitI_opPybyL2Bo6Kuduc">
> * 색상 적용 중 SCZColor로 적용되지 않은 부분들 수정 부탁드림니당
> * 텍스트 TextLiteral로 분리 부탁드립니다
> 
> ## 제안/질문
> * PromotionSection의 가로 캐로셀의 동작이 일반적인 사용 패턴에서 불편하게 느껴질 수 있을 것 같습니다..! 지금 스크롤이 절반 이상 되었을 떄 다음 카드로 스냅되는 것으로 보이는데 생각보다 신경 써서 카드를 넘겨야 다음으로 넘어가네요😭 약간 빠르게 넘기다 보면 종종 원래 위치로 되돌아오는 현상이 생깁니다. 다른 분들 의견도 들어봐야 할 것 같아요.
> * 공통적으로 디자인에 사용되는 요소들을 extension등으로 분리해 재사용성을 높이는 방향이 좋을 것 같습니다!
>   
>   * RoundedRectangle 및 윤곽선 : [[Feat] 커뮤니티 탭 및 글쓰기 view 구현 #516](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/issues/516) 에서 extension으로 구현해놨습니다
>   * 숫자 seal?
>   * 그라디언트 적용 : SCZColor서 이미 같은 기능을 하는 것으로 보이는데 맞나요?
> * 화면의 Background 색상은 다음 태스크에서 적용 예정이신가요?

> > > @HanGyeongjun 디자인 수정사항 말고 레이아웃만 봐주시겠어요? 아직 디자인 확정사항 아니고 색상 확정아니고, 익스텐션 제작된게 없어서 제가 작업하기 편하려고 임의로 작성해서 사용했다고 적어뒀습니다~ 카드섹션은 어떤 상황에서 말하는건지 모르겠어요 다시 한번 설명 부탁드립니다
> > > 확정된 익스텐션 존재한다면 먼저 pr올려주시면 더 좋을 것 같네요
> > 
> > 
> > SCZColor가 임의로 만드신거긴 한데 사용 방법도 편리하고 다양한 색상 사용에 대응이 가능할 것 같아서 저는 계속 유지해도 좋을 것 같다는 의견이었습니다! 사용 색상 확정되면 그 부분만 수정해서 그대로 쓰면 될 것 같아요. 지난번에 티모가 색상 hex값으로 사용하자고 하신 기억도 있어서 괜찮아 보임니당
> > ![Image](https://private-user-images.githubusercontent.com/94854258/319101524-e6fa4c25-4989-4191-8fe3-96c66f74510d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzI5ODksIm5iZiI6MTcxMjEzMjY4OSwicGF0aCI6Ii85NDg1NDI1OC8zMTkxMDE1MjQtZTZmYTRjMjUtNDk4OS00MTkxLThmZTMtOTZjNjZmNzQ1MTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4MjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNTI2MDIyYTJjODY4NWQ2NzEwNGUxZTQ0OGVhZGQxNTA5YTI4YzgwNzBmMzIzMTUzZTVhMDZlNjNlZjA0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.221jAbhN5EXqb4ex6hDaqmFOu1z25DvKxvAWehsR86E) 여기 양쪽 부분에서 카드가 끝까지 보여야 할 것 같습니다! 지금은 양쪽 padding 때문에 끝까지 나타나지 않네요
> > 익스텐션은 지금 작업중인 브랜치라 오늘 밤 중에 pr 올릴 수 있을 것 같아요😭
> 
> 공통으로 적용해야하는 익스텐션을 먼저 작업중이셨다면 브랜치를 분리해서 먼저 올려줬으면 더 좋았을 것 같네요 저 부분이 왜 보여야하는걸까요? 스크롤이 안되는 영역이 아닌데요..?

저부분이 잘리면 곤란합니다..! 갑작스럽게 뚝 끊기게 되면 배경색상과의 이질감이 생겨서 시선이 쏠리게 되고 앱 자체의 완성도도 낮아보여요.
최상단 ScrollView에 .scrollClipDisabled(disabled) modifier를 적용하시면 해결될 것 같습니다.

2024-04-03 08:37 UTC, JMM00 commented
> .scrollClipDisabled(disabled)

해당 모디파이어는 버전이 안맞아서 적용이 안되고 맞춰서 반영하겠습니다

2024-04-03 08:46 UTC, JMM00 commented on HappyAnding/HappyAnding/Model/ExploreShortcutSectionType.swift
> +                Text("새로 올라온")
넵

2024-04-03 11:04 UTC, JMM00 commented on HappyAnding/HappyAnding/Assets.xcassets/Seal.imageset/Seal.png
SF symbol로 수정 했습니다

2024-04-04 02:50 UTC, teethemoji approved these changes
수고하셨습니다 엘리👍

2024-04-04 02:50 UTC, teethemoji commented on HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
> +
SafeArea를 무시하는 BackgroundColor 적용이 필요합니다!
```suggestion
        .background{
            ZStack {
                Color.white
                SCZColor.CharcoalGray.opacity04
            }
            .ignoresSafeArea()
```

2024-04-04 04:38 UTC, JMM00 commented on HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
> +
저부분은 네비게이션 바 색상을 적용하는 부분이라 별도의 부분이고 배경색은 흰색 위에 오파시티가 적용된 다른 색을 올리는게 어색해서 일단 적용을 안하고 있었습니다 레이어를 두개 쌓으면서 색상을 두가지로 적용해야할 이유가 따로 있는지 궁금합니다.

2024-04-04 06:13 UTC, HanGyeongjun approved these changes
수고하셨습니다!

2024-04-13 06:20 UTC, merged